{% set name = "pyXDSM" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdolab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e2a4bf676630f5179ba553313b8ed6049cb7e7748b19a7b707c7111db56996b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.16
    - python >={{ python_min }}

test:
  imports:
    - pyxdsm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mdolab/pyXDSM
  summary: Python script to generate PDF XDSM diagrams using TikZ and LaTeX
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
