{% set name = "pyXDSM" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdolab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cdf71c3bded2445495ce572d67f1f9535b503eabac76a9b89e96e52ae41671b5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.16
    - python >={{ python_min }}

test:
  imports:
    - pyxdsm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mdolab/pyXDSM
  summary: Python script to generate PDF XDSM diagrams using TikZ and LaTeX
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
