{% set name = "pyxdsm" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyXDSM-{{ version }}.tar.gz
  sha256: 9add8efce755d9a45fd02f7bb6a8482bde0eb5c17c37907f18e7cfa1258bfdd5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<=3.8
  run:
    - numpy >=1.16
    - python >=3.6,<=3.8

test:
  imports:
    - pyxdsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdolab/pyXDSM
  summary: Python script to generate PDF XDSM diagrams using TikZ and LaTeX
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
