{% set name = "pyXDSM" %}
{% set version = "2.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdolab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8ec265114dd40ee74c9a3922406b84aec7ab59f78aa819b2a800038a19167f12

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.16
    - python >=3.6

test:
  imports:
    - pyxdsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdolab/pyXDSM
  summary: Python script to generate PDF XDSM diagrams using TikZ and LaTeX
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
