{% set name = "pyxdsm" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyXDSM-{{ version }}.tar.gz
  sha256: b3460511cf2940d3bdc8b3f7cc66955ad7ac738a0746bff8464af9c87217c456

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<=3.8
  run:
    - numpy >=1.9.2
    - python >=3.6,<=3.8

test:
  imports:
    - pyxdsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdolab/pyXDSM
  summary: Python script to generate PDF XDSM diagrams using TikZ and LaTeX
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
